### PR TITLE
Prefer to obtain router directly from container, over the route

### PR DESCRIPTION
**Pull request by mike-north**
In order to avoid future breakage in Ember 3.5, possible collision w/ user-defined properties, and deprecation warnings in Ember 3.1, this small change attempts to obtain the router from the container instead of from the route.

Related deprecation: https://www.emberjs.com/deprecations/v3.x/#toc_ember-routing-route-router

### CODE REVIEW

**Comment by Duder-onomy** [comment]
BOOM! Lets get this merged!

**Comment by Argun** [comment]
"ember-cli": "^3.4.0-beta.1"

`Uncaught TypeError: self.router.setTitle is not a function
    at document-title.js:75
    at tryCatcher (rsvp.js:200)
    at invokeCallback (rsvp.js:372)
    at publish (rsvp.js:358)
    at rsvp.js:14
    at invoke (backburner.js:205)
    at Queue.flush (backburner.js:125)
    at DeferredActionQueues.flush (backburner.js:278)
    at Backburner.end (backburner.js:410)
    at Backburner._run (backburner.js:760)`

**Comment by mike-north** [comment]
@Argun the ember version is more relevant than ember-cli verision, and any optional features and feature flags you may have turned on

**Comment by mike-north** [comment]
@Argun I took the time to update all dependencies of this library to current (#76) based on your report that this doesn't work in Ember 3.4.0-beta.1. Now this addon's test suite runs for a bunch of different dependency scenarios ranging from Ember `1.13.x` through `3.5.0-canary`.

If you still believe this change to be problematic, please create an ember app that demonstrates the issue, publish it on github and respond with a link to it so I can take a closer look. As it stands, I have nowhere near enough information to help you out.

**Comment by dmuneras** [comment]
Hey @mike-north @kimroen ! is there any blocker to merge this PR?

**Comment by mike-north** [comment]
@dmuneras you can always point to my branch in your package.json. 
```js
{
"ember-cli-document-title": "https://github.com/mike-north/ember-cli-document-title#route-router"
}
```

**Comment by BitBrit** [comment]
@mike-north This looks great. Tiny point, should you also update the package version?

**Comment by mike-north** [comment]
> Tiny point, should you also update the package version?

@BitBrit When contributing to libraries maintained by others, I don't want to presume what kind of version change will occur. There could be several releases before this PR gets merged in, and a version that might make sense today would not make sense at the time the code is merged.

**Comment by rmachielse** [comment]
@kimroen can this get some attention? Would like to get rid of the deprecation warning.

**Comment by lepolt** [comment]
Also would like to see this merged...

**Comment by simonc** [comment]
Hi 😊 

Is there anything preventing this PR from being merged? If so is there anything we can do to help?

Thanks! ❤️

**Comment by scalvert** [comment]
I believe this PR should be superseded by #80.

**Comment by btecu** [comment]
@scalvert The challenge is getting any of them merged.

**Comment by scalvert** [comment]
Spoke to @kimroen via Twitter. She's on vacation right now, but will look into all PRs once back.

**Comment by backspace** [comment]
Thanks for letting us know! Side note that according to [Twitter](https://twitter.com/kimroen) as of when I write this, he uses “he/his” pronouns. 💞

**Comment by scalvert** [comment]
Corrected! Thanks, @backspace!
